-- =============================================================================
-- DATA VAULT 2.0 — DELIVERY NETWORK
-- Database: PL_AKHRAMKO_DB  |  Schema: DELIVERY_VAULT
-- 6 Hubs + 4 Links + 12 Satellites + 2 Reference Tables = 24 objects
-- =============================================================================

USE WAREHOUSE CORTEX_CODE_EMEA_WH;

CREATE OR REPLACE SCHEMA PL_AKHRAMKO_DB.DELIVERY_VAULT;

-- =============================================================================
-- REFERENCE TABLES
-- =============================================================================

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.REF_STATUS (
    STATUS_CODE       VARCHAR(10)    NOT NULL PRIMARY KEY,
    STATUS_NAME       VARCHAR(50)    NOT NULL,
    STATUS_CATEGORY   VARCHAR(30)    NOT NULL,
    IS_TERMINAL       BOOLEAN        NOT NULL,
    DISPLAY_ORDER     INT            NOT NULL,
    LOAD_DTS          TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    RECORD_SOURCE     VARCHAR(100)   NOT NULL
);

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.REF_DATE (
    DATE_KEY        INT            NOT NULL PRIMARY KEY,
    FULL_DATE       DATE           NOT NULL,
    DAY_OF_WEEK     TINYINT        NOT NULL,
    DAY_NAME        VARCHAR(10)    NOT NULL,
    DAY_OF_MONTH    TINYINT        NOT NULL,
    DAY_OF_YEAR     SMALLINT       NOT NULL,
    WEEK_OF_YEAR    TINYINT        NOT NULL,
    MONTH_NUMBER    TINYINT        NOT NULL,
    MONTH_NAME      VARCHAR(10)    NOT NULL,
    QUARTER         TINYINT        NOT NULL,
    YEAR            SMALLINT       NOT NULL,
    IS_WEEKEND      BOOLEAN        NOT NULL,
    IS_HOLIDAY      BOOLEAN        NOT NULL,
    LOAD_DTS        TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    RECORD_SOURCE   VARCHAR(100)   NOT NULL
);

-- =============================================================================
-- HUBS
-- Hash keys: MD5 of business key(s), stored as BINARY(16)
-- =============================================================================

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_SHIPMENT (
    HUB_SHIPMENT_HK   BINARY(16)     NOT NULL PRIMARY KEY,
    TRACKING_NUMBER    VARCHAR(30)    NOT NULL,
    LOAD_DTS           TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    RECORD_SOURCE      VARCHAR(100)   NOT NULL
);

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_CUSTOMER (
    HUB_CUSTOMER_HK    BINARY(16)     NOT NULL PRIMARY KEY,
    CUSTOMER_ID         VARCHAR(20)    NOT NULL,
    LOAD_DTS            TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    RECORD_SOURCE       VARCHAR(100)   NOT NULL
);

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_ADDRESS (
    HUB_ADDRESS_HK     BINARY(16)     NOT NULL PRIMARY KEY,
    ADDRESS_BK          VARCHAR(270)   NOT NULL,
    LOAD_DTS            TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    RECORD_SOURCE       VARCHAR(100)   NOT NULL
);

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_CARRIER (
    HUB_CARRIER_HK     BINARY(16)     NOT NULL PRIMARY KEY,
    CARRIER_CODE        VARCHAR(10)    NOT NULL,
    LOAD_DTS            TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    RECORD_SOURCE       VARCHAR(100)   NOT NULL
);

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_SERVICE_TYPE (
    HUB_SERVICE_TYPE_HK BINARY(16)     NOT NULL PRIMARY KEY,
    SERVICE_CODE         VARCHAR(10)    NOT NULL,
    LOAD_DTS             TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    RECORD_SOURCE        VARCHAR(100)   NOT NULL
);

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_PACKAGE_TYPE (
    HUB_PACKAGE_TYPE_HK BINARY(16)     NOT NULL PRIMARY KEY,
    PACKAGE_CODE         VARCHAR(10)    NOT NULL,
    LOAD_DTS             TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    RECORD_SOURCE        VARCHAR(100)   NOT NULL
);

-- =============================================================================
-- LINKS
-- =============================================================================

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.LNK_SHIPMENT (
    LNK_SHIPMENT_HK          BINARY(16)     NOT NULL PRIMARY KEY,
    HUB_SHIPMENT_HK           BINARY(16)     NOT NULL,
    HUB_CUSTOMER_SENDER_HK    BINARY(16)     NOT NULL,
    HUB_CUSTOMER_RECEIVER_HK  BINARY(16)     NOT NULL,
    HUB_CARRIER_HK             BINARY(16)     NOT NULL,
    HUB_SERVICE_TYPE_HK        BINARY(16)     NOT NULL,
    HUB_PACKAGE_TYPE_HK        BINARY(16)     NOT NULL,
    HUB_ADDRESS_ORIGIN_HK      BINARY(16)     NOT NULL,
    HUB_ADDRESS_DEST_HK        BINARY(16)     NOT NULL,
    LOAD_DTS                   TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    RECORD_SOURCE              VARCHAR(100)   NOT NULL,
    CONSTRAINT FK_LNK_SHIP_HUB_SHIP    FOREIGN KEY (HUB_SHIPMENT_HK)          REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_SHIPMENT(HUB_SHIPMENT_HK),
    CONSTRAINT FK_LNK_SHIP_HUB_SENDER  FOREIGN KEY (HUB_CUSTOMER_SENDER_HK)   REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_CUSTOMER(HUB_CUSTOMER_HK),
    CONSTRAINT FK_LNK_SHIP_HUB_RECV    FOREIGN KEY (HUB_CUSTOMER_RECEIVER_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_CUSTOMER(HUB_CUSTOMER_HK),
    CONSTRAINT FK_LNK_SHIP_HUB_CARR    FOREIGN KEY (HUB_CARRIER_HK)            REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_CARRIER(HUB_CARRIER_HK),
    CONSTRAINT FK_LNK_SHIP_HUB_SVC     FOREIGN KEY (HUB_SERVICE_TYPE_HK)       REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_SERVICE_TYPE(HUB_SERVICE_TYPE_HK),
    CONSTRAINT FK_LNK_SHIP_HUB_PKG     FOREIGN KEY (HUB_PACKAGE_TYPE_HK)       REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_PACKAGE_TYPE(HUB_PACKAGE_TYPE_HK),
    CONSTRAINT FK_LNK_SHIP_HUB_ORIG    FOREIGN KEY (HUB_ADDRESS_ORIGIN_HK)     REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_ADDRESS(HUB_ADDRESS_HK),
    CONSTRAINT FK_LNK_SHIP_HUB_DEST    FOREIGN KEY (HUB_ADDRESS_DEST_HK)       REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_ADDRESS(HUB_ADDRESS_HK)
);

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.LNK_CUSTOMER_ADDRESS (
    LNK_CUSTOMER_ADDRESS_HK  BINARY(16)     NOT NULL PRIMARY KEY,
    HUB_CUSTOMER_HK           BINARY(16)     NOT NULL,
    HUB_ADDRESS_HK             BINARY(16)     NOT NULL,
    LOAD_DTS                   TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    RECORD_SOURCE              VARCHAR(100)   NOT NULL,
    CONSTRAINT FK_LNK_CA_HUB_CUST FOREIGN KEY (HUB_CUSTOMER_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_CUSTOMER(HUB_CUSTOMER_HK),
    CONSTRAINT FK_LNK_CA_HUB_ADDR FOREIGN KEY (HUB_ADDRESS_HK)  REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_ADDRESS(HUB_ADDRESS_HK)
);

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.LNK_CARRIER_SERVICE (
    LNK_CARRIER_SERVICE_HK   BINARY(16)     NOT NULL PRIMARY KEY,
    HUB_CARRIER_HK            BINARY(16)     NOT NULL,
    HUB_SERVICE_TYPE_HK        BINARY(16)     NOT NULL,
    LOAD_DTS                   TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    RECORD_SOURCE              VARCHAR(100)   NOT NULL,
    CONSTRAINT FK_LNK_CS_HUB_CARR FOREIGN KEY (HUB_CARRIER_HK)      REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_CARRIER(HUB_CARRIER_HK),
    CONSTRAINT FK_LNK_CS_HUB_SVC  FOREIGN KEY (HUB_SERVICE_TYPE_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_SERVICE_TYPE(HUB_SERVICE_TYPE_HK)
);

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.LNK_SHIPMENT_STATUS (
    LNK_SHIPMENT_STATUS_HK   BINARY(16)     NOT NULL PRIMARY KEY,
    HUB_SHIPMENT_HK           BINARY(16)     NOT NULL,
    STATUS_CODE                VARCHAR(10)    NOT NULL,
    LOAD_DTS                   TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    RECORD_SOURCE              VARCHAR(100)   NOT NULL,
    CONSTRAINT FK_LNK_SS_HUB_SHIP FOREIGN KEY (HUB_SHIPMENT_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_SHIPMENT(HUB_SHIPMENT_HK),
    CONSTRAINT FK_LNK_SS_REF_STAT FOREIGN KEY (STATUS_CODE)      REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.REF_STATUS(STATUS_CODE)
);

-- =============================================================================
-- SATELLITES — HUB_SHIPMENT
-- =============================================================================

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.SAT_SHIPMENT_DETAILS (
    HUB_SHIPMENT_HK    BINARY(16)     NOT NULL,
    LOAD_DTS            TIMESTAMP_NTZ  NOT NULL,
    LOAD_END_DTS        TIMESTAMP_NTZ  NULL,
    RECORD_SOURCE       VARCHAR(100)   NOT NULL,
    HASH_DIFF           BINARY(16)     NOT NULL,
    WEIGHT_KG           FLOAT          NOT NULL,
    DECLARED_VALUE_USD  FLOAT,
    DISTANCE_KM         FLOAT          NOT NULL,
    TRANSIT_DAYS_PLANNED INT           NOT NULL,
    IS_RETURN           BOOLEAN        NOT NULL,
    IS_DAMAGED          BOOLEAN        NOT NULL,
    IS_LOST             BOOLEAN        NOT NULL,
    PRIMARY KEY (HUB_SHIPMENT_HK, LOAD_DTS),
    CONSTRAINT FK_SAT_SD_HUB FOREIGN KEY (HUB_SHIPMENT_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_SHIPMENT(HUB_SHIPMENT_HK)
);

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.SAT_SHIPMENT_FINANCIALS (
    HUB_SHIPMENT_HK    BINARY(16)     NOT NULL,
    LOAD_DTS            TIMESTAMP_NTZ  NOT NULL,
    LOAD_END_DTS        TIMESTAMP_NTZ  NULL,
    RECORD_SOURCE       VARCHAR(100)   NOT NULL,
    HASH_DIFF           BINARY(16)     NOT NULL,
    SHIPPING_COST_USD   FLOAT          NOT NULL,
    INSURANCE_COST_USD  FLOAT          NOT NULL,
    PRIMARY KEY (HUB_SHIPMENT_HK, LOAD_DTS),
    CONSTRAINT FK_SAT_SF_HUB FOREIGN KEY (HUB_SHIPMENT_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_SHIPMENT(HUB_SHIPMENT_HK)
);

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.SAT_SHIPMENT_DELIVERY (
    HUB_SHIPMENT_HK    BINARY(16)     NOT NULL,
    LOAD_DTS            TIMESTAMP_NTZ  NOT NULL,
    LOAD_END_DTS        TIMESTAMP_NTZ  NULL,
    RECORD_SOURCE       VARCHAR(100)   NOT NULL,
    HASH_DIFF           BINARY(16)     NOT NULL,
    SHIP_DATE           DATE           NOT NULL,
    DELIVERY_DATE       DATE,
    TRANSIT_DAYS_ACTUAL INT,
    DELIVERY_ATTEMPTS   INT            NOT NULL,
    PRIMARY KEY (HUB_SHIPMENT_HK, LOAD_DTS),
    CONSTRAINT FK_SAT_SDLV_HUB FOREIGN KEY (HUB_SHIPMENT_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_SHIPMENT(HUB_SHIPMENT_HK)
);

-- =============================================================================
-- SATELLITES — HUB_CUSTOMER
-- =============================================================================

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.SAT_CUSTOMER_DETAILS (
    HUB_CUSTOMER_HK    BINARY(16)     NOT NULL,
    LOAD_DTS            TIMESTAMP_NTZ  NOT NULL,
    LOAD_END_DTS        TIMESTAMP_NTZ  NULL,
    RECORD_SOURCE       VARCHAR(100)   NOT NULL,
    HASH_DIFF           BINARY(16)     NOT NULL,
    FIRST_NAME          VARCHAR(50)    NOT NULL,
    LAST_NAME           VARCHAR(50)    NOT NULL,
    CUSTOMER_TYPE       VARCHAR(20)    NOT NULL,
    EMAIL               VARCHAR(100),
    PHONE               VARCHAR(20),
    PRIMARY KEY (HUB_CUSTOMER_HK, LOAD_DTS),
    CONSTRAINT FK_SAT_CD_HUB FOREIGN KEY (HUB_CUSTOMER_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_CUSTOMER(HUB_CUSTOMER_HK)
);

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.SAT_CUSTOMER_BUSINESS (
    HUB_CUSTOMER_HK    BINARY(16)     NOT NULL,
    LOAD_DTS            TIMESTAMP_NTZ  NOT NULL,
    LOAD_END_DTS        TIMESTAMP_NTZ  NULL,
    RECORD_SOURCE       VARCHAR(100)   NOT NULL,
    HASH_DIFF           BINARY(16)     NOT NULL,
    COMPANY_NAME        VARCHAR(100),
    REGISTRATION_DATE   DATE           NOT NULL,
    LOYALTY_TIER        VARCHAR(20)    NOT NULL,
    PRIMARY KEY (HUB_CUSTOMER_HK, LOAD_DTS),
    CONSTRAINT FK_SAT_CB_HUB FOREIGN KEY (HUB_CUSTOMER_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_CUSTOMER(HUB_CUSTOMER_HK)
);

-- =============================================================================
-- SATELLITES — HUB_ADDRESS
-- =============================================================================

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.SAT_ADDRESS_DETAILS (
    HUB_ADDRESS_HK     BINARY(16)     NOT NULL,
    LOAD_DTS            TIMESTAMP_NTZ  NOT NULL,
    LOAD_END_DTS        TIMESTAMP_NTZ  NULL,
    RECORD_SOURCE       VARCHAR(100)   NOT NULL,
    HASH_DIFF           BINARY(16)     NOT NULL,
    STREET_LINE1        VARCHAR(200)   NOT NULL,
    STREET_LINE2        VARCHAR(200),
    CITY                VARCHAR(100)   NOT NULL,
    STATE_PROVINCE      VARCHAR(50)    NOT NULL,
    POSTAL_CODE         VARCHAR(20)    NOT NULL,
    COUNTRY             VARCHAR(50)    NOT NULL,
    ADDRESS_TYPE        VARCHAR(20)    NOT NULL,
    REGION              VARCHAR(50)    NOT NULL,
    PRIMARY KEY (HUB_ADDRESS_HK, LOAD_DTS),
    CONSTRAINT FK_SAT_AD_HUB FOREIGN KEY (HUB_ADDRESS_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_ADDRESS(HUB_ADDRESS_HK)
);

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.SAT_ADDRESS_GEO (
    HUB_ADDRESS_HK     BINARY(16)     NOT NULL,
    LOAD_DTS            TIMESTAMP_NTZ  NOT NULL,
    LOAD_END_DTS        TIMESTAMP_NTZ  NULL,
    RECORD_SOURCE       VARCHAR(100)   NOT NULL,
    HASH_DIFF           BINARY(16)     NOT NULL,
    LATITUDE            FLOAT,
    LONGITUDE           FLOAT,
    PRIMARY KEY (HUB_ADDRESS_HK, LOAD_DTS),
    CONSTRAINT FK_SAT_AG_HUB FOREIGN KEY (HUB_ADDRESS_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_ADDRESS(HUB_ADDRESS_HK)
);

-- =============================================================================
-- SATELLITES — HUB_CARRIER
-- =============================================================================

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.SAT_CARRIER_DETAILS (
    HUB_CARRIER_HK     BINARY(16)     NOT NULL,
    LOAD_DTS            TIMESTAMP_NTZ  NOT NULL,
    LOAD_END_DTS        TIMESTAMP_NTZ  NULL,
    RECORD_SOURCE       VARCHAR(100)   NOT NULL,
    HASH_DIFF           BINARY(16)     NOT NULL,
    CARRIER_NAME        VARCHAR(100)   NOT NULL,
    CARRIER_TYPE        VARCHAR(30)    NOT NULL,
    HEADQUARTERS        VARCHAR(100)   NOT NULL,
    PRIMARY KEY (HUB_CARRIER_HK, LOAD_DTS),
    CONSTRAINT FK_SAT_CRD_HUB FOREIGN KEY (HUB_CARRIER_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_CARRIER(HUB_CARRIER_HK)
);

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.SAT_CARRIER_OPERATIONS (
    HUB_CARRIER_HK     BINARY(16)     NOT NULL,
    LOAD_DTS            TIMESTAMP_NTZ  NOT NULL,
    LOAD_END_DTS        TIMESTAMP_NTZ  NULL,
    RECORD_SOURCE       VARCHAR(100)   NOT NULL,
    HASH_DIFF           BINARY(16)     NOT NULL,
    FLEET_SIZE          INT            NOT NULL,
    RATING              FLOAT          NOT NULL,
    PRIMARY KEY (HUB_CARRIER_HK, LOAD_DTS),
    CONSTRAINT FK_SAT_CRO_HUB FOREIGN KEY (HUB_CARRIER_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_CARRIER(HUB_CARRIER_HK)
);

-- =============================================================================
-- SATELLITES — HUB_SERVICE_TYPE
-- =============================================================================

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.SAT_SERVICE_TYPE (
    HUB_SERVICE_TYPE_HK BINARY(16)     NOT NULL,
    LOAD_DTS             TIMESTAMP_NTZ  NOT NULL,
    LOAD_END_DTS         TIMESTAMP_NTZ  NULL,
    RECORD_SOURCE        VARCHAR(100)   NOT NULL,
    HASH_DIFF            BINARY(16)     NOT NULL,
    SERVICE_NAME         VARCHAR(50)    NOT NULL,
    DELIVERY_SPEED       VARCHAR(20)    NOT NULL,
    MAX_WEIGHT_KG        FLOAT          NOT NULL,
    MAX_LENGTH_CM        FLOAT          NOT NULL,
    TRACKING_INCLUDED    BOOLEAN        NOT NULL,
    INSURANCE_INCLUDED   BOOLEAN        NOT NULL,
    SIGNATURE_REQUIRED   BOOLEAN        NOT NULL,
    PRIMARY KEY (HUB_SERVICE_TYPE_HK, LOAD_DTS),
    CONSTRAINT FK_SAT_ST_HUB FOREIGN KEY (HUB_SERVICE_TYPE_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_SERVICE_TYPE(HUB_SERVICE_TYPE_HK)
);

-- =============================================================================
-- SATELLITES — HUB_PACKAGE_TYPE
-- =============================================================================

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.SAT_PACKAGE_TYPE (
    HUB_PACKAGE_TYPE_HK BINARY(16)     NOT NULL,
    LOAD_DTS             TIMESTAMP_NTZ  NOT NULL,
    LOAD_END_DTS         TIMESTAMP_NTZ  NULL,
    RECORD_SOURCE        VARCHAR(100)   NOT NULL,
    HASH_DIFF            BINARY(16)     NOT NULL,
    PACKAGE_NAME         VARCHAR(50)    NOT NULL,
    CATEGORY             VARCHAR(20)    NOT NULL,
    MAX_WEIGHT_KG        FLOAT          NOT NULL,
    MAX_DIMENSIONS_CM    VARCHAR(30)    NOT NULL,
    IS_FRAGILE           BOOLEAN        NOT NULL,
    REQUIRES_COOLING     BOOLEAN        NOT NULL,
    PRIMARY KEY (HUB_PACKAGE_TYPE_HK, LOAD_DTS),
    CONSTRAINT FK_SAT_PT_HUB FOREIGN KEY (HUB_PACKAGE_TYPE_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.HUB_PACKAGE_TYPE(HUB_PACKAGE_TYPE_HK)
);

-- =============================================================================
-- SATELLITES — LNK_SHIPMENT_STATUS (Effectivity Satellite)
-- =============================================================================

CREATE OR REPLACE TABLE PL_AKHRAMKO_DB.DELIVERY_VAULT.SAT_SHIPMENT_STATUS_EFF (
    LNK_SHIPMENT_STATUS_HK  BINARY(16)     NOT NULL,
    LOAD_DTS                  TIMESTAMP_NTZ  NOT NULL,
    LOAD_END_DTS              TIMESTAMP_NTZ  NULL,
    RECORD_SOURCE             VARCHAR(100)   NOT NULL,
    HASH_DIFF                 BINARY(16)     NOT NULL,
    STATUS_CATEGORY           VARCHAR(30)    NOT NULL,
    IS_TERMINAL               BOOLEAN        NOT NULL,
    EFFECTIVE_FROM            TIMESTAMP_NTZ  NOT NULL,
    EFFECTIVE_TO              TIMESTAMP_NTZ,
    PRIMARY KEY (LNK_SHIPMENT_STATUS_HK, LOAD_DTS),
    CONSTRAINT FK_SAT_SSE_LNK FOREIGN KEY (LNK_SHIPMENT_STATUS_HK) REFERENCES PL_AKHRAMKO_DB.DELIVERY_VAULT.LNK_SHIPMENT_STATUS(LNK_SHIPMENT_STATUS_HK)
);
